import 'package:animation/src/helper/colors.dart';
import 'package:flutter/material.dart';

class AppTheme {
  static const ColorScheme lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: primaryLight,
    onPrimary: onPrimaryLight,
    primaryContainer: primaryContainerLight,
    onPrimaryContainer: onPrimaryContainerLight,
    primaryFixed: primaryFixedLight,
    primaryFixedDim: primaryFixedDimLight,
    onPrimaryFixed: onPrimaryFixedLight,
    onPrimaryFixedVariant: onPrimaryFixedVariantLight,
    secondary: secondaryLight,
    onSecondary: onSecondaryLight,
    secondaryContainer: secondaryContainerLight,
    onSecondaryContainer: onSecondaryContainerLight,
    secondaryFixed: secondaryFixedLight,
    secondaryFixedDim: secondaryFixedDimLight,
    onSecondaryFixed: onSecondaryFixedLight,
    onSecondaryFixedVariant: onSecondaryFixedVariantLight,
    tertiary: tertiaryLight,
    onTertiary: onTertiaryLight,
    tertiaryContainer: tertiaryContainerLight,
    onTertiaryContainer: onTertiaryContainerLight,
    tertiaryFixed: tertiaryFixedLight,
    tertiaryFixedDim: tertiaryFixedDimLight,
    onTertiaryFixed: onTertiaryFixedLight,
    onTertiaryFixedVariant: onTertiaryFixedVariantLight,
    error: errorLight,
    onError: onErrorLight,
    errorContainer: errorContainerLight,
    onErrorContainer: onErrorContainerLight,
    surface: surfaceLight,
    onSurface: onSurfaceLight,
    onSurfaceVariant: onSurfaceVariantLight,
    outline: outlineLight,
    outlineVariant: outlineVariantLight,
    shadow: shadowLight,
    scrim: scrimLight,
    inverseSurface: inverseSurfaceLight,
    onInverseSurface: onInverseSurfaceLight,
    inversePrimary: inversePrimaryLight,
    surfaceTint: surfaceTintLight,
    surfaceDim: surfaceDimLight,
    surfaceBright: surfaceBrightLight,
    surfaceContainerLowest: surfaceContainerLowestLight,
    surfaceContainerLow: surfaceContainerLowLight,
    surfaceContainer: surfaceContainerLight,
    surfaceContainerHigh: surfaceContainerHighLight,
    surfaceContainerHighest: surfaceContainerHighestLight,
  );

  static const ColorScheme darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: primaryDark,
    onPrimary: onPrimaryDark,
    primaryContainer: primaryContainerDark,
    onPrimaryContainer: onPrimaryContainerDark,
    primaryFixed: primaryFixedDark,
    primaryFixedDim: primaryFixedDimDark,
    onPrimaryFixed: onPrimaryFixedDark,
    onPrimaryFixedVariant: onPrimaryFixedVariantDark,
    secondary: secondaryDark,
    onSecondary: onSecondaryDark,
    secondaryContainer: secondaryContainerDark,
    onSecondaryContainer: onSecondaryContainerDark,
    secondaryFixed: secondaryFixedDark,
    secondaryFixedDim: secondaryFixedDimDark,
    onSecondaryFixed: onSecondaryFixedDark,
    onSecondaryFixedVariant: onSecondaryFixedVariantDark,
    tertiary: tertiaryDark,
    onTertiary: onTertiaryDark,
    tertiaryContainer: tertiaryContainerDark,
    onTertiaryContainer: onTertiaryContainerDark,
    tertiaryFixed: tertiaryFixedDark,
    tertiaryFixedDim: tertiaryFixedDimDark,
    onTertiaryFixed: onTertiaryFixedDark,
    onTertiaryFixedVariant: onTertiaryFixedVariantDark,
    error: errorDark,
    onError: onErrorDark,
    errorContainer: errorContainerDark,
    onErrorContainer: onErrorContainerDark,
    surface: surfaceDark,
    onSurface: onSurfaceDark,
    onSurfaceVariant: onSurfaceVariantDark,
    outline: outlineDark,
    outlineVariant: outlineVariantDark,
    shadow: shadowDark,
    scrim: scrimDark,
    inverseSurface: inverseSurfaceDark,
    onInverseSurface: onInverseSurfaceDark,
    inversePrimary: inversePrimaryDark,
    surfaceTint: surfaceTintDark,
    surfaceDim: surfaceDimDark,
    surfaceBright: surfaceBrightDark,
    surfaceContainerLowest: surfaceContainerLowestDark,
    surfaceContainerLow: surfaceContainerLowDark,
    surfaceContainer: surfaceContainerDark,
    surfaceContainerHigh: surfaceContainerHighDark,
    surfaceContainerHighest: surfaceContainerHighestDark,
  );

  static final TextTheme lightTextTheme = TextTheme(
    displayLarge: TextStyle(
      fontSize: 57,
      fontWeight: FontWeight.bold,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    displayMedium: TextStyle(
      fontSize: 45,
      fontWeight: FontWeight.bold,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    displaySmall: TextStyle(
      fontSize: 36,
      fontWeight: FontWeight.bold,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    headlineLarge: TextStyle(
      fontSize: 32,
      fontWeight: FontWeight.w700,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    headlineMedium: TextStyle(
      fontSize: 28,
      fontWeight: FontWeight.w600,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    headlineSmall: TextStyle(
      fontSize: 24,
      fontWeight: FontWeight.w600,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    titleLarge: TextStyle(
      fontSize: 22,
      fontWeight: FontWeight.w600,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    titleMedium: TextStyle(
      fontSize: 16,
      fontWeight: FontWeight.w500,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    titleSmall: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w500,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    bodyLarge: TextStyle(
      fontSize: 16,
      fontWeight: FontWeight.normal,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    bodyMedium: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.normal,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    bodySmall: TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.normal,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    labelLarge: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w600,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    labelMedium: TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w500,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
    labelSmall: TextStyle(
      fontSize: 11,
      fontWeight: FontWeight.w500,
      color: onSurfaceLight,
      fontFamily: 'NunitoSans',
    ),
  );

  static final TextTheme darkTextTheme = TextTheme(
    displayLarge: TextStyle(
      fontSize: 57,
      fontWeight: FontWeight.bold,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    displayMedium: TextStyle(
      fontSize: 45,
      fontWeight: FontWeight.bold,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    displaySmall: TextStyle(
      fontSize: 36,
      fontWeight: FontWeight.bold,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    headlineLarge: TextStyle(
      fontSize: 32,
      fontWeight: FontWeight.w700,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    headlineMedium: TextStyle(
      fontSize: 28,
      fontWeight: FontWeight.w600,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    headlineSmall: TextStyle(
      fontSize: 24,
      fontWeight: FontWeight.w600,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    titleLarge: TextStyle(
      fontSize: 22,
      fontWeight: FontWeight.w600,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    titleMedium: TextStyle(
      fontSize: 16,
      fontWeight: FontWeight.w500,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    titleSmall: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w500,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    bodyLarge: TextStyle(
      fontSize: 16,
      fontWeight: FontWeight.normal,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    bodyMedium: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.normal,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    bodySmall: TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.normal,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    labelLarge: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w600,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    labelMedium: TextStyle(
      fontSize: 12,
      fontWeight: FontWeight.w500,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
    labelSmall: TextStyle(
      fontSize: 11,
      fontWeight: FontWeight.w500,
      color: onSurfaceDark,
      fontFamily: 'NunitoSans',
    ),
  );

  static final ThemeData lightTheme = ThemeData(
    useMaterial3: true,
    colorScheme: lightColorScheme,
    brightness: Brightness.light,
    scaffoldBackgroundColor: surfaceContainerLowestLight,
    primaryColor: primaryLight,
    cardColor: surfaceLight,
    dialogTheme: DialogTheme(backgroundColor: surfaceLight),
    dividerTheme: DividerThemeData(color: outlineLight),
    fontFamily: 'NunitoSans',
    textTheme: lightTextTheme,
  );

  static final ThemeData darkTheme = ThemeData(
    useMaterial3: true,
    colorScheme: darkColorScheme,
    brightness: Brightness.dark,
    scaffoldBackgroundColor: surfaceContainerLowestDark,
    primaryColor: primaryDark,
    cardColor: surfaceDark,
    dialogTheme: DialogTheme(backgroundColor: surfaceDark),
    dividerTheme: DividerThemeData(color: outlineDark),
    fontFamily: 'NunitoSans',
    textTheme: darkTextTheme,
  );
}
